### ISSUE TITLE
CMake error with "CUDA_cublas_device_LIBRARY"

### ISSUE THREAD

**Issue by harumo11** [clab/dynet#1457]
Hello,
Thanks for good library and developers.

I'm trying to install for C++.
But, I get error messages when I type following command.

```
cmake .. -DEIGEN3_INCLUDE_DIR=/home/robot/opt/eigen3 -DENABLE_CPP_EXAMPLES=ON -DBACKEND=cuda -DCUDNN_ROOT=/usr/local/cuda 
```

And I get following error messages.

```
-- BACKEND: cuda
CUDA_LIBRARIES: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so;/usr/local/cuda/lib64/libcurand.so
-- Found CUDNN (include: /usr/local/cuda/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Successfully include CUDNN flags
-- Eigen dir is /home/robot/opt/eigen3
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "dynet" in directory /home/robot/opt/dynet/dynet
    linked by target "1_linear_regression" in directory /home/robot/opt/dynet/tutorial
    linked by target "0_multiply" in directory /home/robot/opt/dynet/tutorial
    linked by target "xor-multidevice" in directory /home/robot/opt/dynet/examples
    linked by target "xor" in directory /home/robot/opt/dynet/examples
    linked by target "rnnlm-aevb" in directory /home/robot/opt/dynet/examples
    linked by target "fflm" in directory /home/robot/opt/dynet/examples
    linked by target "xor-batch" in directory /home/robot/opt/dynet/examples
    linked by target "imdb" in directory /home/robot/opt/dynet/examples
    linked by target "tok-embed" in directory /home/robot/opt/dynet/examples
    linked by target "rnnlm-batch" in directory /home/robot/opt/dynet/examples
    linked by target "embed-cl" in directory /home/robot/opt/dynet/examples
    linked by target "xor-autobatch" in directory /home/robot/opt/dynet/examples
    linked by target "mnist" in directory /home/robot/opt/dynet/examples
    linked by target "rnnlm-batch-nce" in directory /home/robot/opt/dynet/examples
    linked by target "rnn-autobatch" in directory /home/robot/opt/dynet/examples
    linked by target "poisson-regression" in directory /home/robot/opt/dynet/examples
    linked by target "read-write" in directory /home/robot/opt/dynet/examples
    linked by target "rnnlm" in directory /home/robot/opt/dynet/examples
    linked by target "attention" in directory /home/robot/opt/dynet/examples
    linked by target "encdec" in directory /home/robot/opt/dynet/examples
    linked by target "tag-bilstm" in directory /home/robot/opt/dynet/examples
    linked by target "rnnlm-cfsm" in directory /home/robot/opt/dynet/examples

-- Configuring incomplete, errors occurred!
See also "/home/robot/opt/dynet/build/CMakeFiles/CMakeOutput.log".
See also "/home/robot/opt/dynet/build/CMakeFiles/CMakeError.log".
```

More nvidia library is needed?
I already installed cudnn and cuda tool kit.

By the way, my nvidia environment is as below.

```Fri Sep 21 19:14:05 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
| 23%   28C    P8    12W / 250W |    287MiB / 11175MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1061      G   /usr/lib/xorg/Xorg                           180MiB |
|    0      1282      G   /usr/bin/gnome-shell                          98MiB |
|    0      1940      G   /usr/lib/firefox/firefox                       2MiB |
|    0      2191      G   /usr/lib/firefox/firefox                       2MiB |
+-----------------------------------------------------------------------------+

```

Please tell me how to solve this problem.
Thanks in advance.

**Comment by pmichel31415** [comment]
Hi, can you give your CUDA and compiler version, as well as the output of a clean cmake (remove the build dir, recreate it and rerun cmake)?

**Comment by pmichel31415** [comment]
Please also tell us the exact commit you're trying to install

**Comment by harumo11** [comment]
Hi, @pmichel31415 
Thanks for replaying.
My CUDA version and other information are as below.

- GCC version
  7.3.0
- CUDA tookkit version 
   10.0
- cuDNN verion
  v7.3.0 
- dynet version 
  Sorry, I don't know how to confirm dynet version. 
  I copied dynet from github on last Friday(21 Sep. 2018).
  And I can get following information.
 ```
  git log
 ---------------------------------------------------------------------------------------
  commit c93962933803039cc59bc3cb21277048def086bc (HEAD -> master, origin/master,     origin/HEAD)
  Merge: d9d3e800 bac99679
Author: Paul Michel <pmichel31415@gmail.Com>
Date:   Tue Sep 18 23:23:07 2018 -0400

    Merge pull request #1452 from clab/fix-block-dropout
    
    Fix block dropout on GPU

commit bac99679eb6f9b963e186d8fe336cfe214cba7d4 (origin/fix-block-dropout)
Author: Paul Michel <pmichel31415@gmail.com>
Date:   Tue Sep 18 16:33:13 2018 -0400

    Fix block dropout on GPU

commit d9d3e8004771746fb6c8a491c087632b7018c87f (tag: 2.1)
Author: Brian Lester <blester125@users.noreply.github.com>
Date:   Tue Sep 18 10:51:16 2018 -0400

    Fix glorot initialization for convolutional kernels (#1420)
    
    * fix glorot initialization for convs
    
:
```

```
cat /proc/driver/nvidia/version
---------------------------------------------------------------------------------------------------------
NVRM version: NVIDIA UNIX x86_64 Kernel Module  410.48  Thu Sep  6 06:36:33 CDT 2018
GCC version:  gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3) 
```

I tried to delete build directory and rebuild,
But I got same errors.

**Comment by harumo11** [comment]
And my OS environment is Ubuntu18.04.

**Comment by pmichel31415** [comment]
Yes I suspect this is an issue with CUDA 10.0 @harumo11 if you can confirm that @codelilei 's fix is working for you on Dynet let us know so we can update the documentation

**Comment by texttheater** [comment]
Confirmed: I had the same problem (Ubuntu 18.04, CUDA 10.0) and installing CMake 3.12.2 (instead of the distro's 3.10.2) fixed it.

**Comment by harumo11** [comment]
Thanks @texttheater 

I tried to install CMake 3.12.2,  and the error was not appeared. 
But I got another error in stead of the error as below.

```
$ cmake .. -DEIGEN3_INCLUDE_DIR=/home/robot/opt/eigen3 -DENABLE_CPP_EXAMPLES=ON -DBACKEND=cuda -DCUDNN_ROOT=/usr/local/cuda 
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BACKEND: cuda
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.0") 
CUDA_LIBRARIES: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so;/usr/local/cuda/lib64/libcurand.so
-- Found CUDNN (include: /usr/local/cuda/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Successfully include CUDNN flags
-- Eigen dir is /home/robot/opt/eigen3
-- Configuring done
CMake Warning at /usr/local/share/cmake-3.12/Modules/FindCUDA.cmake:1816 (add_library):
  Cannot generate a safe runtime search path for target dynet because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  dynet/CMakeLists.txt:287 (cuda_add_library)


CMake Warning at tutorial/CMakeLists.txt:4 (add_executable):
  Cannot generate a safe runtime search path for target 1_linear_regression
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.


CMake Warning at tutorial/CMakeLists.txt:4 (add_executable):
  Cannot generate a safe runtime search path for target 0_multiply because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target xor-multidevice
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:44 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target xor because files in
  some directories may conflict with libraries in implicit directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:43 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target rnnlm-aevb because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:41 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target fflm because files in
  some directories may conflict with libraries in implicit directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:26 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target xor-batch because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:24 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target imdb because files in
  some directories may conflict with libraries in implicit directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:25 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target tok-embed because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:42 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target rnnlm-batch because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:23 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target embed-cl because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:34 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target xor-autobatch because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:22 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target mnist because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:27 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target rnnlm-batch-nce
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:28 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target rnn-autobatch because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:21 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target poisson-regression
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:29 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target read-write because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:30 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target rnnlm because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:31 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target attention because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:35 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target encdec because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:36 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target tag-bilstm because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:38 (ADD_EXAMPLE)


CMake Warning at examples/CMakeLists.txt:6 (add_executable):
  Cannot generate a safe runtime search path for target rnnlm-cfsm because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libcudnn.so.7] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  examples/CMakeLists.txt:37 (ADD_EXAMPLE)


-- Generating done
-- Build files have been written to: /home/robot/opt/dynet/build

```

I tried following command.
```
cmake .. -DEIGEN3_INCLUDE_DIR=/home/robot/opt/eigen3 -DENABLE_CPP_EXAMPLES=ON
```
The command gave me no error, although default back-end set libeigen.

Should do I re-install cuDNN?

**Comment by harumo11** [comment]
I solved this CMake error.
Thanks a lot for @pmichel31415, @texttheater and @codelilei.

```
robot@robot-NG:~/opt/dynet/build$ cmake .. -DEIGEN3_INCLUDE_DIR=/home/robot/opt/eigen3 -DENABLE_CPP_EXAMPLES=ON -DBACKEND=cuda -DCUDNN_ROOT=/usr/local/cuda/
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BACKEND: cuda
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.0") 
CUDA_LIBRARIES: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so;/usr/local/cuda/lib64/libcurand.so
-- Found CUDNN (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Successfully include CUDNN flags
-- Eigen dir is /home/robot/opt/eigen3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/robot/opt/dynet/build
```

**Comment by bravegag** [comment]
> I also got the problem when I compiled caffe with the latest CUDA 10.0, and after upgrading CMake from 3.12.1 to 3.12.2 it's done @harumo11

This solved the issue for me too! thank you!

**Comment by suryadesu** [comment]
Hi,
I have been facing similar error while installing Torch on my server.
Cuda version - 11.0
CMake version - 3.18.2
I see the above solutions work for CMake version >=3.12.2
Can someone please help with this.
Thanks
```
-- Found Torch7 in /home/cs17btech11048/torch/install
-- Removing -DNDEBUG from compile flags
-- TH_LIBRARIES: TH
-- MAGMA not found. Compiling without MAGMA support
-- Autodetected CUDA architecture(s): 6.0 6.0
-- got cuda version 11.0
-- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
-- CUDA_NVCC_FLAGS: -gencode;arch=compute_60,code=sm_60;-DCUDA_HAS_FP16=1
-- THC_SO_VERSION: 0
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "THC" in directory /home/cs17btech11048/torch/extra/cutorch/lib/THC

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

Error: Build error: Failed building.
```

**Comment by b4zz4** [comment]
I have the same problem.

**Comment by youyuxiansen** [comment]
find the `${CUDA_CUBLAS_LIBRARIES}` and comment it in your CMakeList.txt

**Comment by hsen-dev** [comment]
solution: https://codeyarns.com/tech/2019-03-20-caffe-cuda_cublas_device_library-error.html
