### ISSUE TITLE
CUDA failure occurs when using auto-batching with the latest version

### ISSUE THREAD

**Issue by owenzx** [clab/dynet#834]
Hi, I've just upgraded to the latest version of DyNet and I can't use auto-batching anymore.

I'm running on GPU with CUDA7.5 and CUDNN5.1

When I run my RNN models with --dynet-autobatch 1, I always get

> CUDA failure in cudaMemcpyAsync(srcs, &(locs)[0], locs.size()*sizeof(float**), cudaMemcpyHostToDevice)
invalid argument
terminate called after throwing an instance of 'dynet::cuda_exception'
  what():  cudaMemcpyAsync(srcs, &(locs)[0], locs.size()*sizeof(float**), cudaMemcpyHostToDevice)
Aborted (core dumped)

Here's a simple example that shows the same problem:
```
import dynet_config
dynet_config.set_gpu()
import dynet as dy
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--dynet-autobatch')
args = parser.parse_args()

pc = dy.ParameterCollection()
trainer = dy.AdamTrainer(pc)

dy.renew_cg()
losses = []
for i in range(2):
    a = dy.zeroes(10)
    losses.append(dy.squared_distance(a, a))
loss = dy.esum(losses)
loss.backward()
trainer.update()
```
It works fine without auto-batching, but with auto-batching, it shows the error above while executing `loss.backward()`
I've tried reinstalling dynet several times but I still have the same problem.

Thanks!

**Comment by neubig** [comment]
Perhaps this was broken by upgrades to multi-device support? @xunzhang, could you take a look? The relevant code is probably in `exec.cc`.

**Comment by shuheik** [comment]
I met a similar bug when I run bilstm-tagger.py in dynet-benchmark (with some modification) on GPU.
It seems that --dynet-gpus must be specified explicitly when --dynet-autobatch is turned on.

It's like
```
$ python -u bilstmtagger.py 128 50 32 1 600 --dynet-autobatch 1
[dynet] random seed: 1752645314
[dynet] using autobatching
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
nwords=119102, ntags=9
startup time: 4.907953977584839
CUDA failure in cudaMemcpyAsync(srcs, &(locs)[0], locs.size()*sizeof(float**), cudaMemcpyHostToDevice)
invalid argument
Traceback (most recent call last):
  File "bilstmtagger.py", line 182, in <module>
    my_loss = loss_exp.scalar_value()
  File "_dynet.pyx", line 1525, in _dynet.Expression.scalar_value (_dynet.cpp:28345)
    cpdef scalar_value(self, recalculate=False):
  File "_dynet.pyx", line 1538, in _dynet.Expression.scalar_value (_dynet.cpp:28244)
    return c_as_scalar(self.cgp().get_value(self.vindex))
RuntimeError: cudaMemcpyAsync(srcs, &(locs)[0], locs.size()*sizeof(float**), cudaMemcpyHostToDevice)
```
vs
```
$ python -u bilstmtagger.py 128 50 32 1 600 --dynet-autobatch 1 --dynet-gpus 1
[dynet] initializing CUDA
Request for 1 GPU ...
[dynet] Device Number: 0
[dynet]   Device name: GeForce GTX 1070
[dynet]   Memory Clock Rate (KHz): 4004000
[dynet]   Memory Bus Width (bits): 256
[dynet]   Peak Memory Bandwidth (GB/s): 256.256
[dynet]   Memory Free (GB): 8.41273/8.50815
[dynet]
[dynet] Device Number: 1
...
[dynet]
[dynet] Device(s) selected: 0
[dynet] random seed: 3577231028
[dynet] using autobatching
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
nwords=119102, ntags=9
startup time: 7.851253986358643
[lr=0.001 clips=0 updates=499] 0.677433358137
...
```

**Comment by owenzx** [comment]
Adding --dynet-gpus solves my problem. Thanks a lot!

**Comment by mattr1** [comment]
Actually, I get the same error in my code if I do --dynet-devices CPU, which is odd because it means even in CPU mode it is trying to do a cudaMemcpyAsync.

**Comment by xunzhang** [comment]
I am looking at it now.Thanks for reporting these.

**Comment by xunzhang** [comment]
@owenzx Hi, I have fixed the bug in the implementation of `dynet_config`, please try the latest master. BTW, the best practice is to use either the `dynet_config` or the `command line options`. If you really want to use both of them for some flexibilities, you can write a command line wrapper of `dynet_config`.

**Comment by xunzhang** [comment]
@mattr1 yes, the problem you met is another inappropriate call of CPU mode under GPU compiled environment. I fixed this via https://github.com/clab/dynet/pull/838. Please try it again, it should work now.

**Comment by owenzx** [comment]
@xunzhang Thank you! The latest master works fine now. Also thanks for your advice on not using both dynet_config and command line options.
